version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    env_file: docker/rabbitmq/.env
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
      - "./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"

  redis:
    build: ./docker/redis
    env_file: docker/redis/.env
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"

  flower:
    image: jcpaiva/celery-flower:latest
    env_file: docker/flower/.env
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis

  api:
    build:
     context: .
     dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - rabbitmq
      - redis
    command: "celery -A app.worker.celery_worker worker --loglevel=info -Q create-order -c 1"

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
